import_datasetname: "tenmado_import"
interim_datasetname: "tenmado_interim"

import_table_names:
  - "t_fewdays_weather"
  - "t_tomorrow_pops"
  - "t_tomorrow_temps"
  - "t_week_weather"
  - "t_week_temps"
  - "t_past_tempavg"
  - "t_past_precopitationavg"
